package com.campfire.entity.enums;

public enum GameState {
    LOBBY,
    DISCLAIMER,
    QUESTION_SUBMISSION,
    SUBMISSION_LOCKED,
    QUESTION_SHUFFLING,
    CHOOSING_SPEAKER,
    QUESTION_ANSWERING,
    QUESTION_DISCUSSION,
    ALL_QUESTIONS_COMPLETE,
    TARGET_REVEAL,
    AUTHOR_REVEAL,
    PERSPECTIVE_COMPARISON,
    SESSION_COMPLETE
}
